// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Gateways.Notification
{
    public enum FormatStatus
    {
        Ok,
        Truncated
    }
}