[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Core")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Web")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Base")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Unit")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Merchello.Tests.Umbraco")]
