// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Acquired.ObjectResolution
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    using LightInject;

    using Merchello.Core.Logging;

    using Umbraco.Core.ObjectResolution;

    /// <summary>
    /// A many objects resolver that uses IoC
    /// </summary>
    /// <typeparam name="TResolver"></typeparam>
    /// <typeparam name="TResolved"></typeparam>
    internal abstract class ContainerManyObjectsResolver<TResolver, TResolved> : ManyObjectsResolverBase<TResolver, TResolved>
        where TResolved : class
        where TResolver : ResolverBase
    {
        private readonly IServiceContainer _container;

        /// <summary>
        /// Constructor for use with IoC
        /// </summary>
        /// <param name="container"></param>
        /// <param name="logger"></param>
        /// <param name="types"></param>
        /// <param name="scope"></param>
        internal ContainerManyObjectsResolver(IServiceContainer container, ILogger logger, IEnumerable<Type> types, ObjectLifetimeScope scope = ObjectLifetimeScope.Application)
            : base(logger, types, scope)
        {
            if (container == null) throw new ArgumentNullException("container");
            this._container = container;
            Resolution.Frozen += this.Resolution_Frozen;

        }
     
        /// <summary>
        /// When resolution is frozen add all the types to the container
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        void Resolution_Frozen(object sender, EventArgs e)
        {
            foreach (var type in this.InstanceTypes)
            {
                this._container.Register(type, GetLifetime(this.LifetimeScope));
            }
        }

        /// <summary>
        /// Convert the ObjectLifetimeScope to ILifetime
        /// </summary>
        /// <param name="scope"></param>
        /// <returns></returns>
        private static ILifetime GetLifetime(ObjectLifetimeScope scope)
        {
            switch (scope)
            {
                case ObjectLifetimeScope.HttpRequest:
                    return new PerRequestLifeTime();
                case ObjectLifetimeScope.Application:
                    return new PerContainerLifetime();
                case ObjectLifetimeScope.Transient:
                default:
                    return null;
            }
        }

        /// <summary>
        /// Creates the instances from IoC
        /// </summary>
        /// <returns>A list of objects of type <typeparamref name="TResolved"/>.</returns>
        protected override IEnumerable<TResolved> CreateValues(ObjectLifetimeScope scope)
        {
            //NOTE: we ignore scope because objects are registered under this scope and not build based on the scope.

            return this._container.GetAllInstances<TResolved>();
        }
    
    }
}