// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Persistence.Migrations
{
    /// <summary>
    /// The install status of the package.
    /// </summary>
    internal enum PluginInstallStatus
    {
         RequiresInstall,
         RequiresUpgrade,
         Current
    }
}