// <auto-generated/> - StyleCop hack to not enforce enum value commentation in this file.
namespace Merchello.Core.Persistence.Migrations
{
    /// <summary>
    /// The database schema status.
    /// </summary>
    internal enum DbSchemaStatus
    {
         RequiresInstall,
         RequiresUpgrade,
         Current
    }
}